### ISSUE TITLE
Exceptions being thrown in onPlayer Join/Leave Events

### ISSUE THREAD

**Issue by AnUnknownMiner** [Turkey2349/Call_Of_Minecraft-Zombies#1]
A EventException is being thrown in these events because Bukkit.getServer().getOnlinePlayers() is throwing a NoSuchMethodError. 

This might not be a fixable issue, and could need a workaround if there isn't one.

**Comment by Turkey2349** [comment]
make sure you are using bukkit version 1.7.10!

**Comment by AnUnknownMiner** [comment]
I'm building with Bukkit 1.7.10, but maybe it's CraftBukkit for me (1.7.9-R0.2)

**Comment by AnUnknownMiner** [comment]
That Fixed the issue.
