### ISSUE TITLE
Bugs and suggestions

### ISSUE THREAD

**Issue by gdude2002** [Turkey2349/Call_Of_Minecraft-Zombies#10]
### Bugs

* New arenas do not work properly unless the plugin is reloaded
    * Doors are not saved
    * Doors that *are* saved are assumed to be open, despite being closed, and don't reset at the end of the round
    * All barriers are treated as "Barrier 0"
* Mystery boxes do not work, throwing an `IndexOutOfBoundsException`
    * This appears to be related to [this line](https://github.com/Turkey2349/Call_Of_Minecraft-Zombies/blob/master/src/com/zombies/game/features/RandomBox.java#L44)
    * They do *sometimes* work, but it's not reliable
* Zombies are kind of stupid, and will tend to ignore players at a distance and may target players in creative mode
    * This may be a Minecraft bug, I'm not entirely sure
* Leaderboards don't work at all, duplicating some players in the list and completely failing to register others
* There is no way to "leave" "spectator mode", which makes adding spectator areas inconvenient as they have to be possible to leave via other means
* Doors break when assigned as an arena door
* Round ends prematurely when 3 players are dead in a 4-player game

### Suggestions

See #9 also

* A larger choice of particles or ItemStacks that are used as projectiles for guns may be nice
* It would be nice if barriers could use the door system of the selection of multiple blocks to use
    * Adding to this, that means that all of the blocks in the barrier would be damaged at the same time, and would all be repaired together with the same sign
* Doors marked as arena doors should open rather than be replaced with air
* Wooden doors marked as arena doors should be impossible to open directly
* To go with the above, redstone should still work with these doors, so that players won't get trapped on badly-designed parkour maps
* It should be possible to link door signs to multiple doors
    * Alternatively, allow door signs to be powered by redstone, and to emit redstone when opened
* Knife range is very low, even skilled players are unable to use it without taking damage - perhaps increase it by one block?
* Auto-updating signs to show players who have gained the most kills may be nice

I'll add more stuff as I think of it

**Comment by gdude2002** [comment]
Just found this one also

![](http://i.imgur.com/dgHhuvP.png)

**Comment by gdude2002** [comment]
@Turkey2349 - are you going to acknowledge these tickets?

**Comment by Turkey2349** [comment]
yes sorry, i have acknowledged them.

**Comment by gdude2002** [comment]
Has this ticket been addressed? The commit messages only seem to refer to a few parts of it.

**Comment by Turkey2349** [comment]
I have fixed and added most of what has been said in this ticket. If you feel i havent addressed or have missed something in this ticket, you can make a new one.
